export const devoteeProfiles = [
  {
    name: "Shri Gaurdas Ji Maharaj",
    handle: "shrigaurdasjimaharaj",
    title: "Shri Gaurdas Ji Maharaj",
    meta: "Followed by yatra devotees",
    role: "Sant and Katha Vachak",
    followers: "154K",
    posts: "482",
    following: "72",
    verified: false,
    followingUser: false,
    avatar: "/images/social/kedarnath.jpg",
  },
  {
    name: "Shri Naresh Bhaiya Ji",
    handle: "shrinareshbhaiyaji",
    title: "Shri Naresh Bhaiya Ji",
    meta: "Followed by siyaram bhakts",
    role: "Spiritual Speaker",
    followers: "19K",
    posts: "126",
    following: "48",
    verified: false,
    followingUser: false,
    avatar: "/images/social/ram-mandir.jpg",
  },
  {
    name: "Hita Ambrish",
    handle: "hitaambrish",
    title: "Hita Ambrish",
    meta: "237K followers",
    role: "Vaishnava Saint",
    followers: "237K",
    posts: "318",
    following: "91",
    verified: true,
    followingUser: false,
    avatar: "/images/social/kashi-vishwanath.jpg",
  },
  {
    name: "Pujya Prembhushan Ji Maharaj",
    handle: "pujya__prembhushanjimaharaj__",
    title: "Pujya Prembhushanji Maharaj",
    meta: "Daily satsang and pravachan",
    role: "Ram Katha Vachak",
    followers: "403K",
    posts: "905",
    following: "58",
    verified: false,
    followingUser: false,
    avatar: "/images/social/somnath.jpg",
  },
  {
    name: "Shri Rajendra Das Ji Maharaj",
    handle: "rajendradasjimaharaj",
    title: "Shri Rajendra Das Ji Maharaj",
    meta: "765K followers",
    role: "Vaishnava Acharya",
    followers: "765K",
    posts: "1.2K",
    following: "36",
    verified: true,
    followingUser: false,
    avatar: "/images/social/tirupati.jpg",
  },
  {
    name: "Bhajan Marg Official",
    handle: "bhajanmarg_official",
    title: "Bhajan Marg Official",
    meta: "40.3M followers",
    role: "Spiritual Organisation",
    followers: "40.3M",
    posts: "3.4K",
    following: "12",
    verified: true,
    followingUser: false,
    avatar: "/images/social/meenakshi.jpg",
  },
  {
    name: "Radhanath Swami",
    handle: "radhanathswami",
    title: "Radhanath Swami",
    meta: "Following",
    role: "Bhakti Teacher",
    followers: "1.1M",
    posts: "1.6K",
    following: "84",
    verified: true,
    followingUser: true,
    avatar: "/images/social/kedarnath.jpg",
  },
  {
    name: "Pundrik Goswami",
    handle: "sripundrik",
    title: "Pundrik Goswami",
    meta: "Following",
    role: "Katha Vachak",
    followers: "802K",
    posts: "776",
    following: "103",
    verified: true,
    followingUser: true,
    avatar: "/images/social/ram-mandir.jpg",
  },
  {
    name: "Indresh Upadhyay",
    handle: "bhaktipath",
    title: "Indresh Upadhyay",
    meta: "Following",
    role: "Bhakti Path",
    followers: "1.8M",
    posts: "2.1K",
    following: "65",
    verified: true,
    followingUser: true,
    avatar: "/images/social/kashi-vishwanath.jpg",
  },
];
